// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXsBRIjAB4vw6LyjDMp0wcpRYJWdvXkUc',
    appId: '1:434034339931:web:dab7ec346c5a9fd7208f7e',
    messagingSenderId: '434034339931',
    projectId: 'dealfinder-71526',
    authDomain: 'dealfinder-71526.firebaseapp.com',
    storageBucket: 'dealfinder-71526.firebasestorage.app',
    measurementId: 'G-KW321NZHVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhrwfaWw7GqBX_z6Ffy6AykYf_u2sEhnQ',
    appId: '1:434034339931:android:e55bfb9d0f840f93208f7e',
    messagingSenderId: '434034339931',
    projectId: 'dealfinder-71526',
    storageBucket: 'dealfinder-71526.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCNsMO_iA-g5roLK6HXJflpVOGVsWw_Ws',
    appId: '1:434034339931:ios:4a61fc606c104bbd208f7e',
    messagingSenderId: '434034339931',
    projectId: 'dealfinder-71526',
    storageBucket: 'dealfinder-71526.firebasestorage.app',
    iosBundleId: 'com.example.dealFinderMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCNsMO_iA-g5roLK6HXJflpVOGVsWw_Ws',
    appId: '1:434034339931:ios:4a61fc606c104bbd208f7e',
    messagingSenderId: '434034339931',
    projectId: 'dealfinder-71526',
    storageBucket: 'dealfinder-71526.firebasestorage.app',
    iosBundleId: 'com.example.dealFinderMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXsBRIjAB4vw6LyjDMp0wcpRYJWdvXkUc',
    appId: '1:434034339931:web:f440edd144ed6ffe208f7e',
    messagingSenderId: '434034339931',
    projectId: 'dealfinder-71526',
    authDomain: 'dealfinder-71526.firebaseapp.com',
    storageBucket: 'dealfinder-71526.firebasestorage.app',
    measurementId: 'G-DT319KEJEV',
  );
}
